/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205745;

public class App {

    public static void main(String[] args) {
        try{
            String str = null; 
            System.out.println(str.length());
        }catch(NullPointerException e){
            System.out.println("例外:NullPointerException\nフィールドの値がnullとなっている為、実行できません。");
            System.out.println(e.getMessage());
        }
        
    }
}
